<div id="loader"></div>
<span>
    <div id='progressCounter'></div>
</span>
<button type="button" id="openModel" class="btn btn-primary" style="display:none;">Open Model</button>
<div id="myModel">
    <h1>Status</h1>
    <div class="categorystatus">Content</div>
</div>
<div id="container" class="main-col">
    <div class="row">
        <div class="col-m-8 col-m-push-2">
            <div id="element" class="collapsibleContainer">
                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Database Connection</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">
                    <table class="bottomBorder">
                        <!-- <caption>Test Connection</caption> -->
                        <thead>
                            <tr>
                                <th scope="col">Host</th>
                                <th scope="col">Database Name</th>
                                <th scope="col">User Name</th>
                                <th scope="col">Password</th>
                                <th scope="col">Port</th>
                                <th scope="col">OsCommerce Version</th>
                                <th scope="col">Test Connection</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?=  /* @noEscape */ $block->getDbHost(); ?></td>
                                <td><?= /* @noEscape */ $block->getDatabase(); ?></td>
                                <td><?= /* @noEscape */ $block->getDbUser(); ?></td>
                                <td><?= /* @noEscape */ $block->getDbPass(); ?></td>
                                <td></td>
                                <td><?= /* @noEscape */ $block->getDbVersion(); ?></td>
                                <td><button class="checkConnection">Test Connection</button></td>
                            </tr>

                        </tbody>
                    </table>
                </div>

                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Categories</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">
                    <table class="bottomBorder">
                        <!-- <caption>Categories</caption> -->
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col">Image Path</th>
                                <th scope="col"># of translations</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?= /* @noEscape */  $block->getCategoryInfo(); ?></td>
                                <td><?= /* @noEscape */  $block->getCategoryImagePath(); ?></td>
                                <td><?= /* @noEscape */  ?></td>
                                <td><?= /* @noEscape */  ?></td>
                                <td></td>
                                <td><?= /* @noEscape */  ?></td>
                                <td><button class="importCategories">Import Categories</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div style="width: 100%;display:none" class="progressdiv">
                                        <div class="status-progress-bar"></div>
                                        <div id="progressbar" class="uk-progress uk-progress-success">
                                            <div class="uk-progress-bar" style="width: 0%;"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Products</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">

                    <table class="bottomBorder">
                        <!-- <caption>Categories</caption> -->
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col">Image Path</th>
                                <th scope="col"># of translations</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?= /* @noEscape */  $block->getProductCount(); ?></td>
                                <td><?= /* @noEscape */  $block->getProductImagePath(); ?></td>
                                <td><?= /* @noEscape */ ?></td>
                                <td><?= /* @noEscape */ ?></td>
                                <td></td>
                                <td><?= /* @noEscape */ ?></td>
                                <td> <button class="importProducts">Import Products</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div style="width: 100%;display:none" class="progressdivproduct">
                                        <div class="product-status-progress-bar"></div>
                                        <div id="progressbarproduct" class="product-progress product-progress-success">
                                            <div class="product-progress-bar" style="width: 0%;"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>


                </div>
                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Custom Options</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">

                    <table class="bottomBorder">
                        <!-- <caption>Categories</caption> -->
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col"></th>
                                <th scope="col"># of translations</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?= /* @noEscape */  $block->getCustomOptionCount(); ?></td>
                                <td><?= /* @noEscape */  ?></td>
                                <td><?= /* @noEscape */ ?></td>
                                <td><?= /* @noEscape */  ?></td>
                                <td></td>
                                <td><?= /* @noEscape */  ?></td>
                                <td> <button class="importProductsCustomizeOptions">Import Customizeable
                                        Options</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div style="width: 100%;display:none" class="progressdivoptions">
                                        <div class="option-status-progress-bar"></div>
                                        <div id="progressbaroption" class="option-progress option-progress-success">
                                            <div class="option-progress-bar" style="width: 0%;"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>


                </div>

            </div>
        </div>
    </div>
</div>
</div>
<?= /* @noEscape */

$isCustomOption = $block->getCustomOptionCount();
if ($isCustomOption == null) {
    $isCustomOption = 0;
}
?>
<script type="text/javascript">
require([
    "jquery",
    "Magento_Ui/js/modal/modal",
    'uikit',
    'accordion'
], function($, modal, uikit) {
    $(document).ready(function() {

        //check database connection
        $('.checkConnection').click(function() {
            var customurl = "<?= /* @noEscape */  $block->getBaseUrl() ?>" + 'admin/dataimport/Ajax/index';
            $.ajax({
                url: customurl,
                type: 'POST',
                dataType: 'json',
                data: {
                    form_key: "<?= /* @noEscape */  $block->getFormKey(); ?>",
                },
                complete: function(response) {
                    console.log(response.responseJSON);
                    msg = response.responseJSON.messageConnection;
                    $('.dataimportdiv').css('display', 'block');
                    alert(msg);
                },
                error: function(xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
        });
        //
        $('.importCategories').click(function() {
            var customurlCat = "<?= /* @noEscape */  $block->getBaseUrl() ?>" +
                'admin/dataimport/Ajax/Addcategories';
            var animate = setInterval(function() {
                var customurl = "<?= /* @noEscape */  $block->getBaseUrl() ?>" +
                    'admin/dataimport/Ajax/Getdata';
                var bar = document.getElementById('progressbar');
                bar.max = "<?= /* @noEscape */  $block->getCategoryInfo(); ?>";
                bar.value = 1; // completed Steps
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        form_key: "<?= /* @noEscape */  $block->getFormKey(); ?>",
                    },
                    success: function(response) {
                        msg = response.counter;
                        if (typeof response.counter == 'undefined') {
                            msg = 0;
                        }
                        barValue = msg;
                        var barmessage = $('.uk-progress-bar');
                        var statusmessage = $('.status-progress-bar');
                        var percent = Math.floor((barValue / bar.max) *
                            100);
                        statusmessage.text(barValue + ' out of ' + bar.max +
                            ' (' + percent + ' %) Completed');
                        barmessage.css({
                            'width': percent + '%',
                            'background': 'green'
                        });

                        if (barValue >= bar.max) {
                            clearInterval(animate);
                        }
                    },
                    error: function(xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });

            }, 1000);

            $.ajax({
                url: customurlCat,
                type: 'POST',
                dataType: 'json',
                data: {
                    form_key: "<?= /* @noEscape */  $block->getFormKey(); ?>",
                },
                beforeSend: function() {
                    $('.importCategories').prop('disabled', true);
                    $('.progressdiv').css('display', 'block');

                },
                complete: function(response) {
                    msg = response.responseJSON.importStatus;
                    $('.dataimportdiv').css('display', 'block');
                    $('#loader').hide();
                    $(".categorystatus").html(msg);
                    $("#openModel").trigger('click');
                    $('.importCategories').prop('disabled', false);
                    clearInterval(animate);

                },
                error: function(xhr, status, errorThrown) {
                    $('.importCategories').prop('disabled', false);
                    clearInterval(animate);

                },
                success: function() {}
            });


        });


        function progress_bar_process(percentage, timer) {
            $('.progress-bar').css('width', percentage + '%');
            if (percentage > 100) {
                clearInterval(timer);
                $('#process').css('display', 'none');
                $('.progress-bar').css('width', '0%');
                $('#save').attr('disabled', false);
                $('#success_message').html("<div class='alert alert-success'>Data Saved</div>");
                setTimeout(function() {
                    $('#success_message').html('');
                }, 5000);
            }
        }
        //import products
        $('.importProducts').click(function() {

            var customurlproduct = "<?= /* @noEscape */  $block->getBaseUrl() ?>" +
                'admin/dataimport/Ajax/Addproducts';
            var animate = setInterval(function() {
                var customurl = "<?= /* @noEscape */  $block->getBaseUrl() ?>" +
                    'admin/dataimport/Ajax/Getproductdata';
                var bar = document.getElementById('progressbarproduct');
                bar.max = "<?= /* @noEscape */  $block->getProductCount(); ?>";
                bar.value = 1; // completed Steps
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        form_key: "<?= /* @noEscape */  $block->getFormKey(); ?>",
                    },
                    success: function(response) {
                        msg = response.counter;
                        console.log(response);
                        if (typeof response.counter == 'undefined') {
                            msg = 0;
                        }
                        barValue = msg;
                        var barmessage = $('.product-progress-bar');
                        var statusmessage = $(
                            '.product-status-progress-bar');
                        var percent = Math.floor((barValue / bar.max) *
                            100);
                        statusmessage.text(barValue + ' out of ' + bar.max +
                            ' (' + percent + ' %) Completed');
                        barmessage.css({
                            'width': percent + '%',
                            'background': 'green'
                        });

                        if (barValue >= bar.max) {
                            clearInterval(animate);
                        }
                    },
                    error: function(xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });

            }, 1000);


            var xhr = $.ajax({
                url: customurlproduct,
                type: 'POST',
                dataType: 'json',
                data: {
                    form_key: "<?= /* @noEscape */  $block->getFormKey(); ?>",
                },
                beforeSend: function() {
                    $('.importProducts').prop('disabled', true);
                    $('.progressdivproduct').css('display', 'block');

                },
                complete: function(response) {
                    msg = response.responseJSON.importStatus;
                    $('.dataimportdiv').css('display', 'block');
                    $(".categorystatus").html(msg);
                    $("#openModel").trigger('click');
                    $('.importProducts').prop('disabled', false);
                    clearInterval(animate);
                },
                error: function(xhr, status, errorThrown) {
                    $('.importProducts').prop('disabled', false);
                    clearInterval(animate);
                }
            });


        });

        //import product customizable options

        $('.importProductsCustomizeOptions').click(function() {

            var customurlOption = "<?= /* @noEscape */  $block->getBaseUrl() ?>" +
                'admin/dataimport/Ajax/Addcustomoption';

            var animate = setInterval(function() {
                var customurl = "<?= /* @noEscape */  $block->getBaseUrl() ?>" +
                    'admin/dataimport/Ajax/Getdataoptions';
                var bar = document.getElementById('progressbaroption');
                bar.max = "<?= /* @noEscape */  $isCustomOption; ?>"" ;
                bar.value = 1; // completed Steps
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        form_key: "<?= /* @noEscape */  $block->getFormKey(); ?>",
                    },
                    success: function(response) {
                        msg = response.counter;
                        if (typeof response.counter == 'undefined') {
                            msg = 0;
                        }
                        barValue = msg;
                        var barmessage = $('.option-progress-bar');
                        var statusmessage = $(
                            '.option-status-progress-bar');
                        var percent = Math.floor((barValue / bar.max) *
                            100);
                        statusmessage.text(barValue + ' out of ' + bar.max +
                            ' (' + percent + ' %) Completed');
                        barmessage.css({
                            'width': percent + '%',
                            'background': 'green'
                        });

                        if (barValue >= bar.max) {
                            clearInterval(animate);
                        }
                    },
                    error: function(xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });

            }, 1000);



            $.ajax({

                url: customurlOption,
                type: 'POST',
                dataType: 'json',
                data: {

                    form_key: "<?= /* @noEscape */  $block->getFormKey(); ?>",
                },
                beforeSend: function() {
                    $('.importProductsCustomizeOptions').prop('disabled', true);
                    $('.progressdivoptions').css('display', 'block');

                },
                complete: function(response) {
                    msg = response.responseJSON.importStatus;
                    $('.dataimportdiv').css('display', 'block');
                    $(".categorystatus").html(msg);
                    $("#openModel").trigger('click');
                    $('.importProductsCustomizeOptions').prop('disabled', false);
                    clearInterval(animate);

                },
                error: function(xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                    $('.importProductsCustomizeOptions').prop('disabled', false);
                    clearInterval(animate);
                }
            });


        });
        $("#element").accordion();
    });
    var options = {
        type: 'popup',
        responsive: true,
        innerScroll: true,
        title: 'Status Product/Category Import',
        buttons: [{
            text: $.mage.__('OK'),
            class: '',
            click: function() {
                this.closeModal();
            }
        }]
    };
    var popup = modal(options, $('#myModel'));
    $("#openModel").on("click", function() {
        $('#myModel').modal('openModal');
    });
});
</script>