<div id="loader"></div>
<span>
    <div id='progressCounter'></div>
</span>
<button type="button" id="openModel" class="btn btn-primary" style="display:none;">Open Model</button>
<div id="myModel">
    <h1>Status</h1>
    <div class="categorystatus">Content</div>
</div>
<div id="container" class="main-col">
    <div class="row">
        <div class="col-m-8 col-m-push-2">
            <div id="element" class="collapsibleContainer">
                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Clean Data</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">

                    <table class="bottomBorder">
                        <!-- <caption>Categories</caption> -->
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Clean All Categories Data</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Clean All Products Data</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td><button class="clean-category-data">Clean All Categories</button></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td> <button class="clean-products-data">Clean All Products </button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div style="width: 100%;display:none" class="progressdivoptions">
                                        <div class="option-status-progress-bar"></div>
                                        <div id="progressbaroption" class="option-progress option-progress-success">
                                            <div class="option-progress-bar" style="width: 0%;"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>


                </div>
                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Database Connection</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">
                    <table class="bottomBorder">
                        <!-- <caption>Test Connection</caption> -->
                        <thead>
                            <tr>
                                <th scope="col">Host</th>
                                <th scope="col">Database Name</th>
                                <th scope="col">User Name</th>
                                <th scope="col">Password</th>
                                <th scope="col">Port</th>
                                <th scope="col">OsCommerce Version</th>
                                <th scope="col">Test Connection</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?=/* @noEscape */$block->getDatabaseHostName();?></td>
                                <td><?=/* @noEscape */$block->getDatabaseName();?></td>
                                <td><?=/* @noEscape */$block->getDatabaseUser();?></td>
                                <td><?=/* @noEscape */$block->getDatabasePassword();?></td>
                                <td></td>
                                <td><?=/* @noEscape */$block->getOsCommerceVersion();?></td>
                                <td><button class="checkConnection">Test Connection</button></td>
                            </tr>

                        </tbody>
                    </table>
                </div>

                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Categories</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">
                    <table class="bottomBorder">
                        <!-- <caption>Categories</caption> -->
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col">Image Path</th>
                                <th scope="col"># of translations</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?=/* @noEscape */$block->getCategoryInfo();?></td>
                                <td><?=/* @noEscape */$block->getCategoryImagePath();?></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td><button class="importCategories">Import Categories</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div style="width: 100%;display:none" class="progressdiv">
                                        <div class="status-progress-bar"></div>
                                        <div id="progressbar" class="uk-progress uk-progress-success">
                                            <div class="uk-progress-bar" style="width: 0%;"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Products</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">

                    <table class="bottomBorder">
                        <!-- <caption>Categories</caption> -->
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col">Image Path</th>
                                <th scope="col"># of translations</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?=/* @noEscape */$block->getProductCount();?></td>
                                <td><?=/* @noEscape */$block->getProductImagePath();?></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td> <button class="importProducts">Import Products</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div style="width: 100%;display:none" class="progressdivproduct">
                                        <div class="product-status-progress-bar"></div>
                                        <div id="progressbarproduct" class="product-progress product-progress-success">
                                            <div class="product-progress-bar" style="width: 0%;"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>


                </div>
                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Custom Options</span>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">

                    <table class="bottomBorder">
                        <!-- <caption>Categories</caption> -->
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col"></th>
                                <th scope="col"># of translations</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?=/* @noEscape */$block->getCustomOptionCount();?></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td> <button class="importProductsCustomizeOptions">Import Customizeable
                                        Options</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div style="width: 100%;display:none" class="progressdivoptions">
                                        <div class="option-status-progress-bar"></div>
                                        <div id="progressbaroption" class="option-progress option-progress-success">
                                            <div class="option-progress-bar" style="width: 0%;"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>


                </div>



            </div>
        </div>
    </div>
</div>
</div>
<?php
$ajaxurl = $block->getAjaxUrl();

?>
<script type="text/x-magento-init">
    {
            "*": {
                "Embraceit_OscommerceToMagento/js/customjs": {
                    "databaseTestUrl": "<?=$block->getBaseUrl()?>admin/dataimport/Ajax/index",
                    "ajaxBaseUrl": "<?=$block->getBaseUrl()?>admin/dataimport/Ajax/",
                    "formKey": "<?=$block->getFormKey()?>",
                    "chunkSize": <?=/* @noEscape */$block->getChunkSize();?>,
                    "totalLimit":<?=/* @noEscape */$block->getChunkSize();?>,
                    "catCount": <?=/* @noEscape */$block->getCategoryInfo();?>,
                    "productCount":<?=/* @noEscape */$block->getProductCount();?>,
                    "customOptionCount":<?=/* @noEscape */$block->getCustomOptionCount();?>,
                    "addCategoriesUrl" : "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/Addcategories",
                    "addProductUrl" : "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/Addproducts",
                    "addProductCustomOptionUrl" : "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/Addcustomoption",
                    "cleanDataUrl" : "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/Cleardata"
                }
            }
        }
</script>