<?php
/**
 * Copyright © Embrace-it, Inc. All rights reserved.
 */

/**
 * @var $block  Embraceitechnologies\OscommerceToMagento\Block\Adminhtml\Datacheck
 */
?>
<div id='chunk-number'></div>
<div id='chunk-size'></div>
<div id='progress-counter'></div>
<button type="button" id="button-modal" class="btn btn-primary button-modal">Open Model</button>
<div id="model-window">
    <div class="import-status"></div>
</div>
<div id="container" class="main-col">
    <div class="row">
        <div class="col-m-8 col-m-push-2">
            <div id="element" class="collapsible-container-accordian">
                <div class="collapsible-tab-accordian" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Clean Data</span>
                    </div>
                </div>
                <div class="collapsible-content-tab" data-role="content">

                    <table class="bottom-border-table">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Clean All Categories Data</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Clean All Products Data</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td><button <?=/* @noEscape */$block->getButtonStatCategory();?>
                                        class="clean-category-data">Clean All Categories</button></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td> <button <?=/* @noEscape */$block->getButtonStatProduct();?>
                                        class="clean-products-data">Clean All Products </button></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="collapsible-tab-accordian" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Database Connection</span>
                    </div>
                </div>
                <div class="collapsible-content-tab" data-role="content">
                    <table class="bottom-border-table">
                        <thead>
                            <tr>
                                <th scope="col">Host</th>
                                <th scope="col">Database Name</th>
                                <th scope="col">User Name</th>
                                <th scope="col">Password</th>
                                <th scope="col">Port</th>
                                <th scope="col">OsCommerce Version</th>
                                <th scope="col">Test Connection</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><?=/* @noEscape */$block->getDatabaseHostName();?></td>
                                <td><?=/* @noEscape */$block->getDatabaseName();?></td>
                                <td><?=/* @noEscape */$block->getDatabaseUser();?></td>
                                <td><?=/* @noEscape */$block->getDatabasePassword();?></td>
                                <td></td>
                                <td><?=/* @noEscape */$block->getOsCommerceVersion();?></td>
                                <td><button class="checkConnection">Test Connection</button></td>
                            </tr>

                        </tbody>
                    </table>
                </div>
                <div class="collapsible-tab-accordian" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Categories</span>
                    </div>
                </div>
                <div class="collapsible-content-tab" data-role="content">
                    <table class="bottom-border-table">
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col">Image Path</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?=/* @noEscape */$block->getCategoryInfo();?></td>
                                <td><?=/* @noEscape */$block->getCategoryImagePath();?></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td><button <?=/* @noEscape */$block->getButtonStatCategory();?>
                                        class="import-categories">Import Categories</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div class="progress-category">
                                        <div class="status-progress-bar"></div>
                                        <div id="progress-bar-category"
                                            class="category-progress  category-progress-success">
                                            <div class="category-progress-bar"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="collapsible-tab-accordian" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Products</span>
                    </div>
                </div>
                <div class="collapsible-content-tab" data-role="content">
                    <table class="bottom-border-table">
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col">Image Path</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?=/* @noEscape */$block->getProductCount();?></td>
                                <td><?=/* @noEscape */$block->getProductImagePath();?></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td> <button <?=/* @noEscape */$block->getButtonStatProduct();?>
                                        class="import-products">Import Products</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div class="progress-product">
                                        <div class="product-status-progress-bar"></div>
                                        <div id="progress-bar-product"
                                            class="product-progress product-progress-success">
                                            <div class="product-progress-bar"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="collapsible-tab-accordian" data-role="collapsible">
                    <div data-role="trigger">
                        <span>Import Custom Options</span>
                    </div>
                </div>
                <div class="collapsible-content-tab" data-role="content">
                    <table class="bottom-border-table">
                        <thead>
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col">&nbsp;</th>
                                <th scope="col">&nbsp;</th>
                                <th scope="col">&nbsp;</th>
                                <th scope="col">&nbsp;</th>
                                <th scope="col">&nbsp;</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?=/* @noEscape */$block->getCustomOptionCount();?></td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td> <button <?=/* @noEscape */$block->getButtonStatCustomOption();?>
                                        class="import-products-options">Import Customizeable
                                        Options</button></td>
                            </tr>
                            <tr>
                                <td colspan="7">
                                    <!--progress bar-->
                                    <div class="progress-options">
                                        <div class="option-status-progress-bar"></div>
                                        <div id="progress-bar-options" class="option-progress option-progress-success">
                                            <div class="option-progress-bar"></div>
                                        </div>
                                    </div>
                                    <!--progress bar-->
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script type="text/x-magento-init">
    {
            "*": {
                "Embraceitechnologies_OscommerceToMagento/js/customjs": {
                    "databaseTestUrl": "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/index",
                    "ajaxBaseUrl": "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/",
                    "formKey": "<?=/* @noEscape */$block->getFormKey()?>",
                    "chunkSize": <?=/* @noEscape */$block->getChunkSize();?>,
                    "totalLimit":<?=/* @noEscape */$block->getChunkSize();?>,
                    "catCount": <?=/* @noEscape */$block->getCategoryInfo();?>,
                    "productCount":<?=/* @noEscape */$block->getProductCount();?>,
                    "customOptionCount":<?=/* @noEscape */$block->getCustomOptionCount();?>,
                    "addCategoriesUrl" : "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/Addcategories",
                    "addProductUrl" : "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/Addproducts",
                    "addProductCustomOptionUrl" : "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/Addcustomoption",
                    "cleanDataUrl" : "<?=/* @noEscape */$block->getBaseUrl()?>admin/dataimport/Ajax/Cleardata"
                }
            }
        }
</script>